//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__GraficoVentasEmpleado_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__GraficoVentasEmpleado_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
  
    var fechas = ViewBag.Fechas as List<string>;       // Asegúrate de que Fechas es una lista de cadenas
    var totalVentas = ViewBag.TotalVentas as List<decimal>; // Asegúrate de que TotalVentas es una lista de decimales
    var margenVentas = ViewBag.MargenVentas as List<decimal>m // Asegúrate de que MargenVentas es una lista de decimalesedia;

   var fechas = ViewBag.Fechas as List<string>;       // Asegúrate de que Fechas es una lista de cadenas
    var totalVentas = ViewBag.TotalVentas as List<decimal>; // Asegúrate de que Total                __o = Html.Raw(Json.Encode(fechas))


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
                      _o = Html.Raw(Json.Encode(ftotalVentas)


#line default
#line hidden

#line 34"C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
                        o = Html.Raw(Json.Encode(ftmargenVentas


#line default
#line hidden

#line 345C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
   DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
                      __o = Html.Raw(Json.Encode(margenVentas));


#line default
#line hidden

#line 5 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\_GraficoVentasEmpleado.cshtml"
                 __o = Url.Action("ObtenerDatosPorMes", "Reporte");


#line default
#line hidden
}
}
}
