//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\Index.cshtml"
   __o = Html.Action("ObtenerPromedioCalificacionEmpleado", "ReporteEmp")


#line default
#line hidden

#line 2 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\Index.cshtml"
   __o = Html.Action("OObtenerResumenVentasEmpleado, "ReporteEmp");


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\Index.cshtml"
   __o = Html.Action("OObtenerGraficoVentasEmpleado);


#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\842B1BA6013079270E80EF4BC9C68B9C12DC\2\ProyectoLavacar\ProyectoLavacar\Views\ReporteEmp\Index.cshtml"
   __o = Html.Action("listar");


#line default
#line hidden
}
}
}
