//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
using ProyectoLavacar.Models;

#line default
#line hidden

public class _Page_Views_Account_Login_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Account_Login_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
  
    ViewBag.Title = "Iniciar sesión";


#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form", @class = "luxury-form" }))
                {
                    

#line default
#line hidden

#line 5 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
               __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 6 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                                            

                    

#line default
#line hidden

#line 7 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                          

                    

#line default
#line hidden

#line 8 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
               __o = Html.ValidationSummary(true, "", new { @class = "luxury-alert" });


#line default
#line hidden

#line 9 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                                                                                      

                    

#line default
#line hidden

#line 10 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.LabelFor(m => m.Email, new { @class = "input-label" });


#line default
#line hidden

#line 11 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                           __o = Html.TextBoxFor(m => m.Email, new { @class = "luxury-input" });


#line default
#line hidden

#line 12 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.ValidationMessageFor(m => m.Email, "", new { @class = "validation-message" });


#line default
#line hidden

#line 13 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                          

                    

#line default
#line hidden

#line 14 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.LabelFor(m => m.Password, new { @class = "input-label" });


#line default
#line hidden

#line 15 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                           __o = Html.PasswordFor(m => m.Password, new { @class = "luxury-input", id = "Password" });


#line default
#line hidden

#line 16 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.ValidationMessageFor(m => m.Password, "", new { @class = "validation-message" });


#line default
#line hidden

#line 17 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                          

                    

#line default
#line hidden

#line 18 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.CheckBoxFor(m => m.RememberMe);


#line default
#line hidden

#line 19 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                          

                    

#line default
#line hidden

#line 20 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                             

                    

#line default
#line hidden

#line 21 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.ActionLink("Registrarse como usuario nuevo", "Register", null, new { @class = "link-text" });


#line default
#line hidden

#line 22 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                       __o = Html.ActionLink("¿Ha olvidado su contraseña?", "ForgotPassword", null, new { @class = "link-text" });


#line default
#line hidden

#line 23 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
                          
                }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 24 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Account\Login.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
