//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
  
    ViewBag.Title = "Create";


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
if (ViewBag.Error != null)
{
    

#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                               __o = ViewBag.Error;


#line default
#line hidden

#line 5 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                                                        
}

#line default
#line hidden

#line 6 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
using (Html.BeginForm())
{
    

#line default
#line hidden

#line 7 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 8 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                            

    

#line default
#line hidden

#line 9 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
       __o = Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = Html.TextBoxFor(model => model.fecha, new { @class = "form-control", type = "date", required = "required" });


#line default
#line hidden

#line 12 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
       __o = Html.LabelFor(model => model.hora, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = Html.TextBoxFor(model => model.hora, new { @class = "form-control", type = "time", required = "required" });


#line default
#line hidden

#line 15 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = Html.ValidationMessageFor(model => model.hora, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
          
}

#line default
#line hidden

#line 17 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = Html.ActionLink("Volver a la lista", "Index");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 18 "C:\Users\Natsu\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\3\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
  
    ViewBag.Title = "Create";

#line default
#line hidden

#line 3 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"

using (Html.BeginForm()) 
{
 

#line default
#line hidden

#line 4 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                               __o = n

#line 4 ;


#line default
#line hidden

#line 5 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                                                        er

#line default
#line hidden

#line 6 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
kenn\AppData\Local\Temp\95B9F76

#line default
#line hidden

#line 7 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = AppData\Local\Temp\95B9;


#line default
#line hidden

#line 8 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
                            Temp\9

#line default
#line hidden

#line 9 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
   __o = fault
#line hidden

#line 7 "C:\Users\jkenn\AppData\Local\Tem;


#line default
#line hidden

#line 10 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
       __o = 


#line default
#line hidden

#line 10 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F;


#line default
#line hidden

#line 11 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = Html.TextBoxFor(model => model.fecha, new { @class = "form-control", type = "date", required = "required" });


#line default
#line hidden

#line 12 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = royecen

#line 14 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AF;


#line default
#line hidden

#line 13 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
       __o = line 19 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLav;


#line default
#line hidden

#line 14 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = e 20 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6efault
#"time"ageFor(model => model.fech;


#line default
#line hidden

#line 15 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
           __o = 95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reser;


#line default
#line hidden

#line 16 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
          pp

#line default
#line hidden

#line 17 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = ew { @class = "text-danger" });


#line de;


#line default
#line hidden
DefineSection("Scripts", () => {


#line 18 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = ributes: new { @class = "control-labe;


#line default
#line hidden
});

}
}
}
#line 26 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
               __o = Html.EditorFor(model => model.estado);


#line default
#line hidden

#line 27 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
               __o = Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" });


#line default
#line hidden

#line 28 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
          
}

#line default
#line hidden

#line 29 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = Html.ActionLink("Back to List", "Index");


#line default
#line hidden
DefineSection("Scripts", () => {


#line 30 "C:\Users\jkenn\AppData\Local\Temp\95B9F76B3F826F667B9FEB16F6AFFADA0309\2\ProyectoLavacar\ProyectoLavacar\Views\Reservas\Create.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
