//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Reporte__GraficoVentasPorMes_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Reporte__GraficoVentasPorMes_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\99945C70FA0BB7FF334C63AD31131354DA75\2\ProyectoLavacar\ProyectoLavacar\Views\Reporte\_GraficoVentasPorMes.cshtml"
  
    var datosGrafico = ViewBag.DatosGrafico as List<dynamic>;


#line default
#line hidden

#line 2 "C:\Users\Natsu\AppData\Local\Temp\99945C70FA0BB7FF334C63AD31131354DA75\2\ProyectoLavacar\ProyectoLavacar\Views\Reporte\_GraficoVentasPorMes.cshtml"
                __o = Html.Raw(Json.Encode(datosGrafico.Select(d => d.Fecha)));


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\99945C70FA0BB7FF334C63AD31131354DA75\2\ProyectoLavacar\ProyectoLavacar\Views\Reporte\_GraficoVentasPorMes.cshtml"
                     __o = Html.Raw(Json.Encode(datosGrafico.Select(d => d.TotalVentas)));


#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\99945C70FA0BB7FF334C63AD31131354DA75\2\ProyectoLavacar\ProyectoLavacar\Views\Reporte\_GraficoVentasPorMes.cshtml"
                          __o = Html.Raw(Json.Encode(datosGrafico.Select(d => d.MargenPorcentual)));


#line default
#line hidden
}
}
}
