//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Compra_Create_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Compra_Create_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
  
    ViewBag.Title = "Crear Compra";


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                    using (Html.BeginForm())
                    {
                        

#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                   __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                

                    

#line default
#line hidden

#line 6 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                   __o = Html.ValidationSummary(true, "", new { @class = "luxury-alert" });


#line default
#line hidden

#line 7 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                           __o = Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "validation-message" });


#line default
#line hidden

#line 8 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                foreach (var servicio in ViewBag.Servicios)
                                {
                                    var listaServicios = Model?.listaServicios ?? new List<int>();
                                    bool isChecked = listaServicios.Contains(servicio.idServicio);

                                    

#line default
#line hidden

#line 9 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                     __o = servicio.idServicio;


#line default
#line hidden

#line 10 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                                        __o = servicio.idServicio;


#line default
#line hidden

#line 11 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                               __o = isChecked ? "checked" : "";


#line default
#line hidden

#line 12 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                                     __o = servicio.idServicio;


#line default
#line hidden

#line 13 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                           __o = servicio.nombre;


#line default
#line hidden

#line 14 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                          
                                }

#line default
#line hidden

#line 15 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "input-label" });


#line default
#line hidden

#line 16 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                                                               __o = Model?.Total ?? 0;


#line default
#line hidden

#line 17 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.ValidationMessageFor(model => model.Total, "", new { @class = "validation-message" });


#line default
#line hidden

#line 18 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.LabelFor(model => model.DescripcionServicio, htmlAttributes: new { @class = "input-label" });


#line default
#line hidden

#line 19 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                       __o = Html.TextAreaFor(model => model.DescripcionServicio, new { @class = "luxury-textarea", rows = "3" });


#line default
#line hidden

#line 20 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.ValidationMessageFor(model => model.DescripcionServicio, "", new { @class = "validation-message" });


#line default
#line hidden

#line 21 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.LabelFor(model => model.idEmpleado, "Empleado", htmlAttributes: new { @class = "input-label" });


#line default
#line hidden

#line 22 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                            if (ViewBag.empleados is string message)
                                            {
                                                

#line default
#line hidden

#line 23 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                 __o = message;


#line default
#line hidden

#line 24 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                                  
                                            }
                                            else
                                            {
                                                

#line default
#line hidden

#line 25 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                           __o = Html.DropDownListFor(model => model.idEmpleado,
                                                    new SelectList(ViewBag.empleados, "Id", "nombre"),
                                                    "Seleccione un empleado",
                                                    new { @class = "luxury-select" });


#line default
#line hidden

#line 26 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                                                     
                                            }

#line default
#line hidden

#line 27 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                   __o = Html.ValidationMessageFor(model => model.idEmpleado, "", new { @class = "validation-message" });


#line default
#line hidden

#line 28 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                              

                        

#line default
#line hidden

#line 29 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                                  
                        

#line default
#line hidden

#line 30 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                                __o = Url.Action("Index");


#line default
#line hidden

#line 31 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                              
                    
                    }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 32 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
   __o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden

#line 33 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                     __o = Url.Action("BuscarClientePorCedula", "Compra");


#line default
#line hidden

#line 34 "C:\Users\Natsu\AppData\Local\Temp\E068F24696BA6937E8AE57F46045A56D4185\2\ProyectoLavacar\ProyectoLavacar\Views\Compra\Create.cshtml"
                         __o = Url.Action("ObtenerPrecioServicio", "Compra");


#line default
#line hidden
});

}
}
}
