//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
  
    ViewBag.Title = "Administración de Compras";


#line default
#line hidden

#line 3 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                    __o = Url.Action("Create");


#line default
#line hidden

#line 4 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                   __o = Html.DisplayNameFor(model => model.Nombre);


#line default
#line hidden

#line 5 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                   __o = Html.DisplayNameFor(model => model.PrimerApellido);


#line default
#line hidden

#line 6 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                   __o = Html.DisplayNameFor(model => model.Total);


#line default
#line hidden

#line 7 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                   __o = Html.DisplayNameFor(model => model.Fecha);


#line default
#line hidden

#line 8 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                foreach (var item in Model)
                                {
                                    

#line default
#line hidden

#line 9 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                       __o = Html.DisplayFor(modelItem => item.Nombre);


#line default
#line hidden

#line 10 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                       __o = Html.DisplayFor(modelItem => item.PrimerApellido);


#line default
#line hidden

#line 11 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                                            __o = Html.DisplayFor(modelItem => item.Total);


#line default
#line hidden

#line 12 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                       __o = Html.DisplayFor(modelItem => item.Fecha);


#line default
#line hidden

#line 13 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                                __o = Url.Action("DetallesCompra", new { idCompra = item.idCompra });


#line default
#line hidden

#line 14 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                                __o = Url.Action("DescargarPDFCompra", new { idCompra = item.idCompra });


#line default
#line hidden

#line 15 "C:\Users\Natsu\AppData\Local\Temp\59A16CBCF7517259F2B00BB2A11ECAA57755\3\ProyectoLavacar\ProyectoLavacar\Views\Compra\Index.cshtml"
                                         
                                }

#line default
#line hidden
}
}
}
